//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26/04/2017 22:58:13
namespace CodeGames2017.CustomerRating.Model
{
    /// <summary>
    /// There are no comments for ApplicationSingle in the schema.
    /// </summary>
    public partial class ApplicationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Application>
    {
        /// <summary>
        /// Initialize a new ApplicationSingle object.
        /// </summary>
        public ApplicationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ApplicationSingle object.
        /// </summary>
        public ApplicationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ApplicationSingle object.
        /// </summary>
        public ApplicationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Application> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Features in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Feature> Features
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Features == null))
                {
                    this._Features = Context.CreateQuery<global::CodeGames2017.CustomerRating.Model.Feature>(GetPath("Features"));
                }
                return this._Features;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Feature> _Features;
    }
    /// <summary>
    /// There are no comments for Application in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ApplicationId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ApplicationId")]
    public partial class Application : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Application object.
        /// </summary>
        /// <param name="applicationId">Initial value of ApplicationId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Application CreateApplication(global::System.Guid applicationId)
        {
            Application application = new Application();
            application.ApplicationId = applicationId;
            return application;
        }
        /// <summary>
        /// There are no comments for Property ApplicationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid ApplicationId
        {
            get
            {
                return this._ApplicationId;
            }
            set
            {
                this.OnApplicationIdChanging(value);
                this._ApplicationId = value;
                this.OnApplicationIdChanged();
                this.OnPropertyChanged("ApplicationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Guid value);
        partial void OnApplicationIdChanged();
        /// <summary>
        /// There are no comments for Property ApplicationName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ApplicationName
        {
            get
            {
                return this._ApplicationName;
            }
            set
            {
                this.OnApplicationNameChanging(value);
                this._ApplicationName = value;
                this.OnApplicationNameChanged();
                this.OnPropertyChanged("ApplicationName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ApplicationName;
        partial void OnApplicationNameChanging(string value);
        partial void OnApplicationNameChanged();
        /// <summary>
        /// There are no comments for Property Features in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Feature> Features
        {
            get
            {
                return this._Features;
            }
            set
            {
                this.OnFeaturesChanging(value);
                this._Features = value;
                this.OnFeaturesChanged();
                this.OnPropertyChanged("Features");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Feature> _Features = new global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Feature>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFeaturesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Feature> value);
        partial void OnFeaturesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for FeatureSingle in the schema.
    /// </summary>
    public partial class FeatureSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Feature>
    {
        /// <summary>
        /// Initialize a new FeatureSingle object.
        /// </summary>
        public FeatureSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new FeatureSingle object.
        /// </summary>
        public FeatureSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new FeatureSingle object.
        /// </summary>
        public FeatureSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Feature> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::CodeGames2017.CustomerRating.Model.ApplicationSingle Application
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Application == null))
                {
                    this._Application = new global::CodeGames2017.CustomerRating.Model.ApplicationSingle(this.Context, GetPath("Application"));
                }
                return this._Application;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::CodeGames2017.CustomerRating.Model.ApplicationSingle _Application;
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Rating> Ratings
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Ratings == null))
                {
                    this._Ratings = Context.CreateQuery<global::CodeGames2017.CustomerRating.Model.Rating>(GetPath("Ratings"));
                }
                return this._Ratings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Rating> _Ratings;
    }
    /// <summary>
    /// There are no comments for Feature in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FeatureId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("FeatureId")]
    public partial class Feature : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Feature object.
        /// </summary>
        /// <param name="featureId">Initial value of FeatureId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Feature CreateFeature(global::System.Guid featureId)
        {
            Feature feature = new Feature();
            feature.FeatureId = featureId;
            return feature;
        }
        /// <summary>
        /// There are no comments for Property FeatureId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid FeatureId
        {
            get
            {
                return this._FeatureId;
            }
            set
            {
                this.OnFeatureIdChanging(value);
                this._FeatureId = value;
                this.OnFeatureIdChanged();
                this.OnPropertyChanged("FeatureId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _FeatureId;
        partial void OnFeatureIdChanging(global::System.Guid value);
        partial void OnFeatureIdChanged();
        /// <summary>
        /// There are no comments for Property FeatureName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string FeatureName
        {
            get
            {
                return this._FeatureName;
            }
            set
            {
                this.OnFeatureNameChanging(value);
                this._FeatureName = value;
                this.OnFeatureNameChanged();
                this.OnPropertyChanged("FeatureName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FeatureName;
        partial void OnFeatureNameChanging(string value);
        partial void OnFeatureNameChanged();
        /// <summary>
        /// There are no comments for Property Application in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::CodeGames2017.CustomerRating.Model.Application Application
        {
            get
            {
                return this._Application;
            }
            set
            {
                this.OnApplicationChanging(value);
                this._Application = value;
                this.OnApplicationChanged();
                this.OnPropertyChanged("Application");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::CodeGames2017.CustomerRating.Model.Application _Application;
        partial void OnApplicationChanging(global::CodeGames2017.CustomerRating.Model.Application value);
        partial void OnApplicationChanged();
        /// <summary>
        /// There are no comments for Property Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Rating> Ratings
        {
            get
            {
                return this._Ratings;
            }
            set
            {
                this.OnRatingsChanging(value);
                this._Ratings = value;
                this.OnRatingsChanged();
                this.OnPropertyChanged("Ratings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Rating> _Ratings = new global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Rating>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRatingsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::CodeGames2017.CustomerRating.Model.Rating> value);
        partial void OnRatingsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RatingSingle in the schema.
    /// </summary>
    public partial class RatingSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Rating>
    {
        /// <summary>
        /// Initialize a new RatingSingle object.
        /// </summary>
        public RatingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RatingSingle object.
        /// </summary>
        public RatingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RatingSingle object.
        /// </summary>
        public RatingSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Rating> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::CodeGames2017.CustomerRating.Model.ApplicationSingle Application
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Application == null))
                {
                    this._Application = new global::CodeGames2017.CustomerRating.Model.ApplicationSingle(this.Context, GetPath("Application"));
                }
                return this._Application;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::CodeGames2017.CustomerRating.Model.ApplicationSingle _Application;
        /// <summary>
        /// There are no comments for Feature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::CodeGames2017.CustomerRating.Model.FeatureSingle Feature
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Feature == null))
                {
                    this._Feature = new global::CodeGames2017.CustomerRating.Model.FeatureSingle(this.Context, GetPath("Feature"));
                }
                return this._Feature;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::CodeGames2017.CustomerRating.Model.FeatureSingle _Feature;
    }
    /// <summary>
    /// There are no comments for Rating in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RatingId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("RatingId")]
    public partial class Rating : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Rating object.
        /// </summary>
        /// <param name="ratingId">Initial value of RatingId.</param>
        /// <param name="ratingValue">Initial value of RatingValue.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Rating CreateRating(global::System.Guid ratingId, int ratingValue)
        {
            Rating rating = new Rating();
            rating.RatingId = ratingId;
            rating.RatingValue = ratingValue;
            return rating;
        }
        /// <summary>
        /// There are no comments for Property RatingId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid RatingId
        {
            get
            {
                return this._RatingId;
            }
            set
            {
                this.OnRatingIdChanging(value);
                this._RatingId = value;
                this.OnRatingIdChanged();
                this.OnPropertyChanged("RatingId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _RatingId;
        partial void OnRatingIdChanging(global::System.Guid value);
        partial void OnRatingIdChanged();
        /// <summary>
        /// There are no comments for Property RatingValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int RatingValue
        {
            get
            {
                return this._RatingValue;
            }
            set
            {
                this.OnRatingValueChanging(value);
                this._RatingValue = value;
                this.OnRatingValueChanged();
                this.OnPropertyChanged("RatingValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _RatingValue;
        partial void OnRatingValueChanging(int value);
        partial void OnRatingValueChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property RatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string RatedBy
        {
            get
            {
                return this._RatedBy;
            }
            set
            {
                this.OnRatedByChanging(value);
                this._RatedBy = value;
                this.OnRatedByChanged();
                this.OnPropertyChanged("RatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _RatedBy;
        partial void OnRatedByChanging(string value);
        partial void OnRatedByChanged();
        /// <summary>
        /// There are no comments for Property ClientCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ClientCode
        {
            get
            {
                return this._ClientCode;
            }
            set
            {
                this.OnClientCodeChanging(value);
                this._ClientCode = value;
                this.OnClientCodeChanged();
                this.OnPropertyChanged("ClientCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ClientCode;
        partial void OnClientCodeChanging(string value);
        partial void OnClientCodeChanged();
        /// <summary>
        /// There are no comments for Property Application in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::CodeGames2017.CustomerRating.Model.Application Application
        {
            get
            {
                return this._Application;
            }
            set
            {
                this.OnApplicationChanging(value);
                this._Application = value;
                this.OnApplicationChanged();
                this.OnPropertyChanged("Application");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::CodeGames2017.CustomerRating.Model.Application _Application;
        partial void OnApplicationChanging(global::CodeGames2017.CustomerRating.Model.Application value);
        partial void OnApplicationChanged();
        /// <summary>
        /// There are no comments for Property Feature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::CodeGames2017.CustomerRating.Model.Feature Feature
        {
            get
            {
                return this._Feature;
            }
            set
            {
                this.OnFeatureChanging(value);
                this._Feature = value;
                this.OnFeatureChanged();
                this.OnPropertyChanged("Feature");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::CodeGames2017.CustomerRating.Model.Feature _Feature;
        partial void OnFeatureChanging(global::CodeGames2017.CustomerRating.Model.Feature value);
        partial void OnFeatureChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::CodeGames2017.CustomerRating.Model.Application as global::CodeGames2017.CustomerRating.Model.ApplicationSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::CodeGames2017.CustomerRating.Model.ApplicationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Application> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::CodeGames2017.CustomerRating.Model.ApplicationSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::CodeGames2017.CustomerRating.Model.Application as global::CodeGames2017.CustomerRating.Model.ApplicationSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="applicationId">The value of applicationId</param>
        public static global::CodeGames2017.CustomerRating.Model.ApplicationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Application> source,
            global::System.Guid applicationId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ApplicationId", applicationId }
            };
            return new global::CodeGames2017.CustomerRating.Model.ApplicationSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::CodeGames2017.CustomerRating.Model.Feature as global::CodeGames2017.CustomerRating.Model.FeatureSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::CodeGames2017.CustomerRating.Model.FeatureSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Feature> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::CodeGames2017.CustomerRating.Model.FeatureSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::CodeGames2017.CustomerRating.Model.Feature as global::CodeGames2017.CustomerRating.Model.FeatureSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="featureId">The value of featureId</param>
        public static global::CodeGames2017.CustomerRating.Model.FeatureSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Feature> source,
            global::System.Guid featureId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "FeatureId", featureId }
            };
            return new global::CodeGames2017.CustomerRating.Model.FeatureSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::CodeGames2017.CustomerRating.Model.Rating as global::CodeGames2017.CustomerRating.Model.RatingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::CodeGames2017.CustomerRating.Model.RatingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Rating> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::CodeGames2017.CustomerRating.Model.RatingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::CodeGames2017.CustomerRating.Model.Rating as global::CodeGames2017.CustomerRating.Model.RatingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="ratingId">The value of ratingId</param>
        public static global::CodeGames2017.CustomerRating.Model.RatingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Rating> source,
            global::System.Guid ratingId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "RatingId", ratingId }
            };
            return new global::CodeGames2017.CustomerRating.Model.RatingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace CodeGames2017CustomerRating
{
    /// <summary>
    /// There are no comments for CodeGames2017CustomerRatingContainer in the schema.
    /// </summary>
    public partial class CodeGames2017CustomerRatingContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CodeGames2017CustomerRatingContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public CodeGames2017CustomerRatingContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Applications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Application> Applications
        {
            get
            {
                if ((this._Applications == null))
                {
                    this._Applications = base.CreateQuery<global::CodeGames2017.CustomerRating.Model.Application>("Applications");
                }
                return this._Applications;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Application> _Applications;
        /// <summary>
        /// There are no comments for Features in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Feature> Features
        {
            get
            {
                if ((this._Features == null))
                {
                    this._Features = base.CreateQuery<global::CodeGames2017.CustomerRating.Model.Feature>("Features");
                }
                return this._Features;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Feature> _Features;
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Rating> Ratings
        {
            get
            {
                if ((this._Ratings == null))
                {
                    this._Ratings = base.CreateQuery<global::CodeGames2017.CustomerRating.Model.Rating>("Ratings");
                }
                return this._Ratings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CodeGames2017.CustomerRating.Model.Rating> _Ratings;
        /// <summary>
        /// There are no comments for Applications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToApplications(global::CodeGames2017.CustomerRating.Model.Application application)
        {
            base.AddObject("Applications", application);
        }
        /// <summary>
        /// There are no comments for Features in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToFeatures(global::CodeGames2017.CustomerRating.Model.Feature feature)
        {
            base.AddObject("Features", feature);
        }
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRatings(global::CodeGames2017.CustomerRating.Model.Rating rating)
        {
            base.AddObject("Ratings", rating);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""CodeGames2017.CustomerRating.Model"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Application"">
        <Key>
          <PropertyRef Name=""ApplicationId"" />
        </Key>
        <Property Name=""ApplicationId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""ApplicationName"" Type=""Edm.String"" />
        <NavigationProperty Name=""Features"" Type=""Collection(CodeGames2017.CustomerRating.Model.Feature)"" />
      </EntityType>
      <EntityType Name=""Feature"">
        <Key>
          <PropertyRef Name=""FeatureId"" />
        </Key>
        <Property Name=""FeatureId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""FeatureName"" Type=""Edm.String"" />
        <NavigationProperty Name=""Application"" Type=""CodeGames2017.CustomerRating.Model.Application"" />
        <NavigationProperty Name=""Ratings"" Type=""Collection(CodeGames2017.CustomerRating.Model.Rating)"" />
      </EntityType>
      <EntityType Name=""Rating"">
        <Key>
          <PropertyRef Name=""RatingId"" />
        </Key>
        <Property Name=""RatingId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""RatingValue"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Comment"" Type=""Edm.String"" />
        <Property Name=""RatedBy"" Type=""Edm.String"" />
        <Property Name=""ClientCode"" Type=""Edm.String"" />
        <NavigationProperty Name=""Application"" Type=""CodeGames2017.CustomerRating.Model.Application"" />
        <NavigationProperty Name=""Feature"" Type=""CodeGames2017.CustomerRating.Model.Feature"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""CodeGames2017CustomerRating"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""CodeGames2017CustomerRatingContainer"">
        <EntitySet Name=""Applications"" EntityType=""CodeGames2017.CustomerRating.Model.Application"">
          <NavigationPropertyBinding Path=""Features"" Target=""Features"" />
        </EntitySet>
        <EntitySet Name=""Features"" EntityType=""CodeGames2017.CustomerRating.Model.Feature"">
          <NavigationPropertyBinding Path=""Application"" Target=""Applications"" />
          <NavigationPropertyBinding Path=""Ratings"" Target=""Ratings"" />
        </EntitySet>
        <EntitySet Name=""Ratings"" EntityType=""CodeGames2017.CustomerRating.Model.Rating"">
          <NavigationPropertyBinding Path=""Application"" Target=""Applications"" />
          <NavigationPropertyBinding Path=""Feature"" Target=""Features"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
